export enum ClinicService {
  VACCINATION = 'VACCINATION',
  SURGERY = 'SURGERY',
  CONSULTATION = 'CONSULTATION',
  EMERGENCY = 'EMERGENCY',
  GROOMING = 'GROOMING',
  BOARDING = 'BOARDING',
  DIAGNOSTICS = 'DIAGNOSTICS',
  PET_PHARMACY = 'PET_PHARMACY',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum DoctorSpecialization {
  GENERAL_PRACTICE = 'GENERAL_PRACTICE',
  SURGERY = 'SURGERY',
  DERMATOLOGY = 'DERMATOLOGY',
  CARDIOLOGY = 'CARDIOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  ONCOLOGY = 'ONCOLOGY',
  OPHTHALMOLOGY = 'OPHTHALMOLOGY',
  DENTISTRY = 'DENTISTRY',
  ORTHOPEDICS = 'ORTHOPEDICS',
  INTERNAL_MEDICINE = 'INTERNAL_MEDICINE',
  EMERGENCY = 'EMERGENCY',
  NUTRITION = 'NUTRITION',
  BEHAVIOR = 'BEHAVIOR',
  EXOTIC_ANIMALS = 'EXOTIC_ANIMALS',
}

export enum ReviewTargetType {
  CLINIC = 'CLINIC',
  ASSISTANT = 'ASSISTANT',
  SHOP = 'SHOP',
  PRODUCT = 'PRODUCT',
}

export enum HomeVisitStatus {
  REQUESTED = 'REQUESTED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum VerificationDocStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum VerificationDocType {
  REGISTRATION_CERTIFICATE = 'REGISTRATION_CERTIFICATE',
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  PAN_CARD = 'PAN_CARD',
  AADHAAR = 'AADHAAR',
  SHOP_ACT_LICENSE = 'SHOP_ACT_LICENSE',
  DRUG_LICENSE = 'DRUG_LICENSE',
  VETERINARY_LICENSE = 'VETERINARY_LICENSE',
  OWNER_PHOTO_ID = 'OWNER_PHOTO_ID',
  CLINIC_LICENSE = 'CLINIC_LICENSE',
  VET_COUNCIL_REGISTRATION = 'VET_COUNCIL_REGISTRATION',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  DEGREE_CERTIFICATE = 'DEGREE_CERTIFICATE',
  OTHER = 'OTHER',
}
