export enum ClinicService {
  VACCINATION = 'VACCINATION',
  SURGERY = 'SURGERY',
  CONSULTATION = 'CONSULTATION',
  EMERGENCY = 'EMERGENCY',
  GROOMING = 'GROOMING',
  BOARDING = 'BOARDING',
  DIAGNOSTICS = 'DIAGNOSTICS',
  PET_PHARMACY = 'PET_PHARMACY',
}

export enum DayOfWeek {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
  SUNDAY = 'SUNDAY',
}

export enum DoctorSpecialization {
  GENERAL_PRACTICE = 'GENERAL_PRACTICE',
  SURGERY = 'SURGERY',
  DERMATOLOGY = 'DERMATOLOGY',
  CARDIOLOGY = 'CARDIOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  ONCOLOGY = 'ONCOLOGY',
  OPHTHALMOLOGY = 'OPHTHALMOLOGY',
  DENTISTRY = 'DENTISTRY',
  ORTHOPEDICS = 'ORTHOPEDICS',
  INTERNAL_MEDICINE = 'INTERNAL_MEDICINE',
  EMERGENCY = 'EMERGENCY',
  NUTRITION = 'NUTRITION',
  BEHAVIOR = 'BEHAVIOR',
  EXOTIC_ANIMALS = 'EXOTIC_ANIMALS',
}

export enum ReviewTargetType {
  CLINIC = 'CLINIC',
  ASSISTANT = 'ASSISTANT',
}
