export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  PET_OWNER = 'PET_OWNER',
  CLINIC_OWNER = 'CLINIC_OWNER',
  ASSISTANT = 'ASSISTANT',
  SHOP_OWNER = 'SHOP_OWNER',
  DELIVERY_PARTNER = 'DELIVERY_PARTNER',
}
